##----------------------------------------------------------------
##' Title: 03_aggregator_HIV_comorbidities.F2T.R
##'
##' Purpose:
##' This script aggregates and summarizes disease occurrence data 
##' across all processed **F2T and RX** datasets for Medicare beneficiaries with HIV.
##' It provides a consolidated summary of the most frequent co-occurring conditions.
##'
##' The script performs the following steps:
##'  1. Reads all CSV files generated by the disease count worker (`02_worker_disease_counts_F2T.R`).
##'  2. Aggregates total and unique disease occurrences across all input files.
##'  3. Computes summary statistics on total encounters and costs per disease.
##'  4. Saves a structured summary table.
##'
##' Inputs:
##'  - Multiple CSV files from `/output_aim1/YYYYMMDD/diseases_count/`.
##'
##' Outputs:
##'  - A Table summarizing:
##'      - Total occurrences per disease.
##'      - Total patient encounters per disease.
##'      - Cost distribution per disease.
##' Author: Bulat Idrisov
##' Date: 2025-03-27
##' Version: 3.0
##'
##----------------------------------------------------------------
rm(list = ls())
pacman::p_load(dplyr, openxlsx, RMySQL, data.table, ini, DBI, tidyr, openxlsx,readr,purrr)
library(lbd.loader, lib.loc = sprintf("/share/geospatial/code/geospatial-libraries/lbd.loader-%s", R.version$major))
if("dex.dbr"%in% (.packages())) detach("package:dex.dbr", unload=TRUE)
library(dex.dbr, lib.loc = lbd.loader::pkg_loc("dex.dbr"))
suppressMessages(lbd.loader::load.containing.package())

# Set drive paths
if (Sys.info()["sysname"] == 'Linux'){
  j <- "/home/j/"
  h <- paste0("/ihme/homes/",Sys.info()[7],"/")
  l <- '/ihme/limited_use/'
} else if (Sys.info()["sysname"] == 'Darwin'){
  j <- "/Volumes/snfs"
  h <- paste0("/Volumes/",Sys.info()[7],"/")
  l <- '/Volumes/limited_use'
} else {
  j <- "J:/"
  h <- "H:/"
  l <- 'L:/'
}

###########
#defined manually
date_of_input_rx <- "20250402"
date_of_input_f2t <-"20250327"
base_dir <- "/mnt/share/limited_use/LU_CMS/DEX/hivsud/aim1/output_aim1"

# Define input directory 
input_folder_f2t <- file.path(base_dir, date_of_input_f2t, "01.Summary_Statistics") #F2T
input_folder_rx <- file.path(base_dir, date_of_input_rx, "01.RX_Summary_Statistics") #rx


# Define output directory
# Get today's date in YYYYMMDD format
today <- format(Sys.Date(), "%Y%m%d")
output_folder <- file.path(base_dir, today, "Agregator(summary_stats)")
figures_folder <- file.path(output_folder, "figures")


dir.create(output_folder, recursive = TRUE, showWarnings = FALSE)
dir.create(figures_folder, recursive = TRUE, showWarnings = FALSE)

# Ensure the output directory exists
ensure_dir_exists <- function(dir_path) {
  if (!dir.exists(dir_path)) {
    dir.create(dir_path, recursive = TRUE)
  }
}

# ensure_dir_exists(output_folder)
# ensure_dir_exists(figures_folder)

# Get the list of all CSV files from the input directory
files_list <- list.files(input_folder_f2t, pattern = "\\.csv$", full.names = TRUE) #F2T
files_list_rx <- list.files(input_folder_rx, pattern = "\\.csv$", full.names = TRUE) #RX

# List all CSV files in the input directory
#files_list <- list.files(input_folder, full.names = TRUE, pattern = "*.csv")

# If no files found, exit with a message
if (length(files_list) == 0) {
  stop("No CSV files found in directory: ", input_folder)
}
if (length(files_list_rx) == 0) {
  stop("No CSV files found in directory: ", input_folder)
}


##########################################
# 1. Read in all CSV files
##########################################

# Read and tag F2T files
df_f2t <- map_dfr(files_list, ~read_csv(.x, show_col_types = FALSE) %>%
                    mutate(source = "f2t"))

# Read and tag RX files
df_rx <- map_dfr(files_list_rx, ~read_csv(.x, show_col_types = FALSE) %>%
                   mutate(source = "rx"))

# Combine into one master table
df_master <- bind_rows(df_f2t, df_rx)



# 
# #df_master <- map_dfr(files_list, read_csv, show_col_types = FALSE)#rx
# df_master <- map_dfr(files_list_rx, read_csv, show_col_types = FALSE)#rx

# Save raw aggregated master file
#write_csv(df_master, file.path(output_folder, "summary_master_table.csv"))




# Inflation adjustment setup
inflation_raw <- data.frame(
  year_id = 2008:2024,
  inflation_rate = c(0.001, 0.027, 0.015, 0.03, 0.017, 0.015, 0.008, 0.007, 0.021, 0.021,
                     0.019, 0.023, 0.014, 0.07, 0.065, 0.034, 0.029)
)

years_present <- sort(unique(df_master$year_id))
inflation_data <- inflation_raw %>%
  filter(year_id %in% years_present) %>%
  arrange(year_id) %>%
  mutate(
    inflation_factor = cumprod(1 + inflation_rate),
    deflator = inflation_factor / inflation_factor[year_id == 2019]
  ) %>%
  select(year_id, deflator)

# Adjust dollar values for inflation

###check quant99
cost_columns <- c("avg_cost_per_bene","quant99", "max_cost_per_bene", "total_cost")

df_adj <- df_master %>%
  left_join(inflation_data, by = "year_id") %>%
  mutate(across(all_of(cost_columns), ~ ./deflator))


# Create weighted summary table for F2T summary statistics (robust to NA mismatches)
summary_table <- df_adj %>%
  group_by(acause, year_id, toc, hiv_flag, age_group, race_cd) %>%
  summarise(
    avg_cost_per_bene = weighted.mean(avg_cost_per_bene, total_unique_bene, na.rm = TRUE),
    max_cost_per_bene = max(max_cost_per_bene, na.rm = TRUE),
    quant99 = weighted.mean(quant99, total_unique_bene, na.rm = TRUE),  # new
    total_cost = sum(total_cost, na.rm = TRUE),
    avg_encounters_per_bene = weighted.mean(avg_encounters_per_bene, total_unique_bene, na.rm = TRUE),
    total_encounters = sum(total_encounters, na.rm = TRUE),
    total_unique_bene = sum(total_unique_bene, na.rm = TRUE),
    mean_any_cost = {
      temp_df <- tibble(val = mean_any_cost, wt = total_unique_bene) %>%
        filter(!is.na(val), !is.na(wt), wt > 0)
      if (nrow(temp_df) == 0) NA_real_ else weighted.mean(temp_df$val, temp_df$wt)
    },
    .groups = "drop"
  )


# Save the summary table
write_csv(summary_table, file.path(output_folder, "f2t_rx_weighted_summary_table.csv"))


##########


# Define metadata columns that do not vary within each file
metadata_cols <- c(
  "total_unique_bene", "total_bene_acause_combo", "mean_any_cost",
  "hiv_unique_bene", "run_id", "toc", "year_id", "code_system", "age_group"
)

# Extract metadata per unique run config (each file = 1 row)
metadata_df <- df_master %>%
  select(all_of(metadata_cols)) %>%
  distinct()

# Add HIV prevalence column (row-wise)
metadata_df <- metadata_df %>%
  mutate(
    hiv_prevalence = if_else(
      total_unique_bene > 0,
      hiv_unique_bene / total_unique_bene,
      NA_real_
    )
  )

# Save metadata table with HIV prevalence
write_csv(metadata_df, file.path(output_folder, "aggregated_metadata_table.csv"))



############
#save_plot(plot1, "Mean_Incremental_Cost_by_Disease_TOC.png")

##----------------------------------------------------------------
##   Create descriptive summary tables (Table 1 style) and plots
##   for the finalized dataset used in the JAMA paper.
##----------------------------------------------------------------

# Plotting Function
save_plot <- function(plot_obj, filename) {
  ggsave(filename = file.path(figures_folder, filename),
         plot = plot_obj, width = 9, height = 6, dpi = 300,
         device = "jpeg")
}

# Table 1: Total Sample Size and Sample Sizes by Various Groups
# Overall Sample Size
total_sample <- summary_table %>%
  summarise(Total_Sample = sum(total_unique_bene, na.rm = TRUE))

# Sample Size by Age Group
sample_by_age <- summary_table %>%
  group_by(age_group) %>%
  summarise(Sample_Size = sum(total_unique_bene, na.rm = TRUE))

# Sample Size by Type of Care (toc)
sample_by_toc <- summary_table %>%
  group_by(toc) %>%
  summarise(Sample_Size = sum(total_unique_bene, na.rm = TRUE))

# Sample Size by HIV Flag
sample_by_hiv <- summary_table %>%
  group_by(hiv_flag) %>%
  summarise(Sample_Size = sum(total_unique_bene, na.rm = TRUE))

# Sample Size by Disease Category (acause)
sample_by_acause <- summary_table %>%
  group_by(acause) %>%
  summarise(Sample_Size = sum(total_unique_bene, na.rm = TRUE))

# Race (to be added later)
# sample_by_race <- summary_table %>%
#   group_by(race_cd) %>%
#   summarise(Sample_Size = sum(total_unique_bene, na.rm = TRUE))

sample_by_race <- summary_table %>%
  group_by(race_cd) %>%
  summarise(Sample_Size = sum(total_unique_bene, na.rm = TRUE))

write_csv(sample_by_race, file.path(output_folder, "Sample_By_Race.csv"))


# Combine into a single table (as needed)
write_csv(total_sample, file.path(output_folder, "Total_Sample.csv"))
write_csv(sample_by_age, file.path(output_folder, "Sample_By_Age.csv"))
write_csv(sample_by_toc, file.path(output_folder, "Sample_By_TypeOfCare.csv"))
write_csv(sample_by_hiv, file.path(output_folder, "Sample_By_HIV_Flag.csv"))
write_csv(sample_by_acause, file.path(output_folder, "Sample_By_Disease.csv"))

# Descriptive statistics (Costs)
cost_descriptives <- summary_table %>%
  summarise(
    Avg_Cost_Per_Bene = mean(avg_cost_per_bene, na.rm = TRUE),
    Median_Cost_Per_Bene = median(avg_cost_per_bene, na.rm = TRUE),
    Max_Cost_Per_Bene = max(max_cost_per_bene, na.rm = TRUE),
    Total_Costs = sum(total_cost, na.rm = TRUE)
  )

write_csv(cost_descriptives, file.path(output_folder, "Cost_Descriptive_Stats.csv"))

# Plots
# Plot 1: Average Cost per Beneficiary by Disease Category
plot1 <- summary_table %>%
  ggplot(aes(x = reorder(acause, avg_cost_per_bene), y = avg_cost_per_bene, fill = acause)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(title = "Average Cost per Beneficiary by Disease Category",
       x = "Disease Category", y = "Average Cost (2019 USD)") +
  theme_minimal() + theme(legend.position = "none")

save_plot(plot1, "Avg_Cost_per_Bene_by_Disease.png")


# Plot 2: Total Costs Over Time
plot2 <- summary_table %>%
  group_by(year_id) %>%
  summarise(total_cost = sum(total_cost, na.rm = TRUE)) %>%
  ggplot(aes(x = year_id, y = total_cost)) +
  geom_line(size = 1.5, color = "blue") + geom_point(size = 3, color = "blue") +
  labs(title = "Total Costs Over Time (2019 USD)", x = "Year", y = "Total Costs") +
  theme_minimal()

save_plot(plot2, "Total_Costs_Over_Time.png")

# Plot 3: Average Encounters per Beneficiary by Age Group
plot3 <- summary_table %>%
  ggplot(aes(x = factor(age_group), y = log(avg_encounters_per_bene), fill = factor(age_group))) +
  geom_boxplot() +
  labs(title = "Log Average Encounters per Beneficiary by Age Group",
       x = "Age Group", y = "Avg Encounters") +
  theme_minimal() + theme(legend.position = "none")

save_plot(plot3, "Log_Avg_Encounters_by_Age_Group.png")

plot4 <- summary_table %>%
  ggplot(aes(x = acause, y = avg_cost_per_bene, fill = race_cd)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  labs(title = "Average Cost per Beneficiary by Disease and Race",
       x = "Disease Category", y = "Average Cost (2019 USD)", fill = "Race") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

save_plot(plot4, "Avg_Cost_per_Bene_by_Disease_and_Race.png")


#### histograms

# Histogram of average cost per beneficiary
hist1 <- summary_table %>%
  ggplot(aes(x = avg_cost_per_bene)) +
  geom_histogram(bins = 50, fill = "steelblue", color = "white") +
  labs(title = "Distribution of Average Cost per Beneficiary",
       x = "Average Cost", y = "Count") +
  theme_minimal()

save_plot(hist1, "Hist_Avg_Cost_Per_Bene.jpeg")

# Log-transformed average cost
hist2 <- summary_table %>%
  ggplot(aes(x = log1p(avg_cost_per_bene))) +
  geom_histogram(bins = 50, fill = "darkgreen", color = "white") +
  labs(title = "Log-Transformed Distribution of Avg Cost per Beneficiary",
       x = "log(1 + Avg Cost)", y = "Count") +
  theme_minimal()

save_plot(hist2, "Hist_Log_Avg_Cost_Per_Bene.jpeg")

# Histogram of average encounters per beneficiary
hist3 <- summary_table %>%
  ggplot(aes(x = avg_encounters_per_bene)) +
  geom_histogram(bins = 50, fill = "tomato", color = "white") +
  labs(title = "Distribution of Average Encounters per Beneficiary",
       x = "Avg Encounters", y = "Count") +
  theme_minimal()

save_plot(hist3, "Hist_Avg_Encounters_Per_Bene.jpeg")

# Scatter: Encounters vs Cost
scatter1 <- summary_table %>%
  ggplot(aes(x = avg_encounters_per_bene, y = avg_cost_per_bene)) +
  geom_point(alpha = 0.6, color = "purple") +
  scale_y_log10() + scale_x_log10() +
  labs(title = "Encounters vs Average Cost (log-log scale)",
       x = "Avg Encounters", y = "Avg Cost") +
  theme_minimal()

save_plot(scatter1, "Scatter_Encounters_vs_Cost.jpeg")


# Completion message
cat("Descriptive tables and plots successfully saved to:", output_folder, "\n")
