##----------------------------------------------------------------
##' Title: 03_aggregator_HIV_comorbidities.F2T.R
##'
##' Purpose:
##' This script aggregates and summarizes disease occurrence data 
##' across all processed **F2T and RX** datasets for Medicare beneficiaries with HIV.
##' It provides a consolidated summary of the most frequent co-occurring conditions.
##'
##' The script performs the following steps:
##'  1. Reads all CSV files generated by the disease count worker (`02_worker_disease_counts_F2T.R`).
##'  2. Aggregates total and unique disease occurrences across all input files.
##'  3. Computes summary statistics on total encounters and costs per disease.
##'  4. Saves a structured summary table.
##'
##' Inputs:
##'  - Multiple CSV files from `/output_aim1/YYYYMMDD/diseases_count/`.
##'
##' Outputs:
##'  - A Table summarizing:
##'      - Total occurrences per disease.
##'      - Total patient encounters per disease.
##'      - Cost distribution per disease.
##' Author: Bulat Idrisov
##' Date: 2025-03-27
##' Version: 3.0
##'
##----------------------------------------------------------------
rm(list = ls())
pacman::p_load(dplyr, openxlsx, RMySQL, data.table, ini, DBI, tidyr, openxlsx,readr,purrr)
library(lbd.loader, lib.loc = sprintf("/share/geospatial/code/geospatial-libraries/lbd.loader-%s", R.version$major))
if("dex.dbr"%in% (.packages())) detach("package:dex.dbr", unload=TRUE)
library(dex.dbr, lib.loc = lbd.loader::pkg_loc("dex.dbr"))
suppressMessages(lbd.loader::load.containing.package())

# Set drive paths
if (Sys.info()["sysname"] == 'Linux'){
  j <- "/home/j/"
  h <- paste0("/ihme/homes/",Sys.info()[7],"/")
  l <- '/ihme/limited_use/'
} else if (Sys.info()["sysname"] == 'Darwin'){
  j <- "/Volumes/snfs"
  h <- paste0("/Volumes/",Sys.info()[7],"/")
  l <- '/Volumes/limited_use'
} else {
  j <- "J:/"
  h <- "H:/"
  l <- 'L:/'
}

###########
#defined manually
date_of_input_rx <- "20250402"
date_of_input_f2t <-"20250327"
base_dir <- "/mnt/share/limited_use/LU_CMS/DEX/hivsud/aim1/output_aim1"

# Define input directory 
input_folder_f2t <- file.path(base_dir, date_of_input_f2t, "01.Summary_Statistics") #F2T
input_folder_rx <- file.path(base_dir, date_of_input_rx, "01.RX_Summary_Statistics") #rx


# Define output directory
# Get today's date in YYYYMMDD format
today <- format(Sys.Date(), "%Y%m%d")
output_folder <- file.path(base_dir, today, "Agregator(summary_stats)")
figures_folder <- file.path(output_folder, "figures")


dir.create(output_folder, recursive = TRUE, showWarnings = FALSE)
dir.create(figures_folder, recursive = TRUE, showWarnings = FALSE)

# Ensure the output directory exists
ensure_dir_exists <- function(dir_path) {
  if (!dir.exists(dir_path)) {
    dir.create(dir_path, recursive = TRUE)
  }
}

# ensure_dir_exists(output_folder)
# ensure_dir_exists(figures_folder)

# Get the list of all CSV files from the input directory
files_list <- list.files(input_folder_f2t, pattern = "\\.csv$", full.names = TRUE) #F2T
files_list_rx <- list.files(input_folder_rx, pattern = "\\.csv$", full.names = TRUE) #RX

# List all CSV files in the input directory
#files_list <- list.files(input_folder, full.names = TRUE, pattern = "*.csv")

# If no files found, exit with a message
if (length(files_list) == 0) {
  stop("No CSV files found in directory: ", input_folder)
}
if (length(files_list_rx) == 0) {
  stop("No CSV files found in directory: ", input_folder)
}


##########################################
# 1. Read in all CSV files
##########################################

# Read and tag F2T files
df_f2t <- map_dfr(files_list, ~read_csv(.x, show_col_types = FALSE) %>%
                    mutate(source = "f2t"))

# Read and tag RX files
df_rx <- map_dfr(files_list_rx, ~read_csv(.x, show_col_types = FALSE) %>%
                   mutate(source = "rx"))

# Combine into one master table
df_master <- bind_rows(df_f2t, df_rx)



# 
# #df_master <- map_dfr(files_list, read_csv, show_col_types = FALSE)#rx
# df_master <- map_dfr(files_list_rx, read_csv, show_col_types = FALSE)#rx

# Save raw aggregated master file
#write_csv(df_master, file.path(output_folder, "summary_master_table.csv"))




# Inflation adjustment setup
inflation_raw <- data.frame(
  year_id = 2008:2024,
  inflation_rate = c(0.001, 0.027, 0.015, 0.03, 0.017, 0.015, 0.008, 0.007, 0.021, 0.021,
                     0.019, 0.023, 0.014, 0.07, 0.065, 0.034, 0.029)
)

years_present <- sort(unique(df_master$year_id))
inflation_data <- inflation_raw %>%
  filter(year_id %in% years_present) %>%
  arrange(year_id) %>%
  mutate(
    inflation_factor = cumprod(1 + inflation_rate),
    deflator = inflation_factor / inflation_factor[year_id == 2019]
  ) %>%
  select(year_id, deflator)

# Adjust dollar values for inflation

###check quant99
cost_columns <- c("avg_cost_per_bene","quant99", "max_cost_per_bene", "total_cost")

df_adj <- df_master %>%
  left_join(inflation_data, by = "year_id") %>%
  mutate(across(all_of(cost_columns), ~ ./deflator))


# Create weighted summary table for F2T summary statistics (robust to NA mismatches)
summary_table <- df_adj %>%
  group_by(acause, year_id, toc, hiv_flag, age_group, race_cd) %>%
  summarise(
    avg_cost_per_bene = weighted.mean(avg_cost_per_bene, total_unique_bene, na.rm = TRUE),
    max_cost_per_bene = max(max_cost_per_bene, na.rm = TRUE),
    quant99 = weighted.mean(quant99, total_unique_bene, na.rm = TRUE),  # new
    total_cost = sum(total_cost, na.rm = TRUE),
    avg_encounters_per_bene = weighted.mean(avg_encounters_per_bene, total_unique_bene, na.rm = TRUE),
    total_encounters = sum(total_encounters, na.rm = TRUE),
    total_unique_bene = sum(total_unique_bene, na.rm = TRUE),
    mean_any_cost = {
      temp_df <- tibble(val = mean_any_cost, wt = total_unique_bene) %>%
        filter(!is.na(val), !is.na(wt), wt > 0)
      if (nrow(temp_df) == 0) NA_real_ else weighted.mean(temp_df$val, temp_df$wt)
    },
    .groups = "drop"
  )


# Save the summary table
write_csv(summary_table, file.path(output_folder, "f2t_rx_weighted_summary_table.csv"))


##########


# Define metadata columns that do not vary within each file
metadata_cols <- c(
  "total_unique_bene", "total_bene_acause_combo", "mean_any_cost",
  "hiv_unique_bene", "run_id", "toc", "year_id", "code_system", "age_group"
)

# Extract metadata per unique run config (each file = 1 row)
metadata_df <- df_master %>%
  select(all_of(metadata_cols)) %>%
  distinct()

# Add HIV prevalence column (row-wise)
metadata_df <- metadata_df %>%
  mutate(
    hiv_prevalence = if_else(
      total_unique_bene > 0,
      hiv_unique_bene / total_unique_bene,
      NA_real_
    )
  )

# Save metadata table with HIV prevalence
write_csv(metadata_df, file.path(output_folder, "aggregated_metadata_table.csv"))
